doctrine:
    dbal:
        types:
            signal: Kstrwbry\BinanceTrader\Type\SignalType
#    orm:
#        resolve_target_entities:
#            Kstrwbry\BinanceTrader\Interface\KlineInterface: App\Entity\Kline
#            Kstrwbry\BinanceTrader\Interface\KlineRawInterface: App\Entity\KlineRaw
